# geolocate_plugin.py

import requests

class GeolocatePlugin:
    name = "GeolocatePlugin"

    def __init__(self):
        self._report = ""

    def run(self, input_data):
        ip = input_data.get("ip", "")
        if not ip:
            self._report = "No IP address provided."
            return self._report

        try:
            url = f"http://ip-api.com/json/{ip}"
            response = requests.get(url, timeout=5).json()

            self._report = (
                f"## 🌍 Geolocation Report\n"
                f"**IP Address:** `{ip}`\n\n"
                f"- **Country:** {response.get('country', 'N/A')}\n"
                f"- **Region:** {response.get('regionName', 'N/A')}\n"
                f"- **City:** {response.get('city', 'N/A')}\n"
                f"- **ZIP Code:** {response.get('zip', 'N/A')}\n"
                f"- **Latitude:** {response.get('lat', 'N/A')}\n"
                f"- **Longitude:** {response.get('lon', 'N/A')}\n"
                f"- **Timezone:** {response.get('timezone', 'N/A')}\n"
                f"- **ISP:** {response.get('isp', 'N/A')}\n\n"
                f"_Report generated by GeolocatePlugin v1.0_"
            )
            return self._report

        except Exception as e:
            self._report = f"❌ Error fetching geolocation: {e}"
            return self._report

    def report(self):
        return self._report

    def cleanup(self):
        pass

def get_plugin():
    return GeolocatePlugin()
