import random

def extract_numerical_features_from_text(text: str) -> dict:
    # Simulate 78 meaningful features (matches your model)
    np_random = random.Random(abs(hash(text)) % (10 ** 8))  # consistent seed per input
    return {
        ' Destination Port': np_random.uniform(0, 65535),
        ' Flow Duration': np_random.uniform(1000, 100000),
        ' Total Fwd Packets': np_random.uniform(1, 1000),
        ' Total Backward Packets': np_random.uniform(1, 1000),
        'Total Length of Fwd Packets': np_random.uniform(100, 10000),
        ' Total Length of Bwd Packets': np_random.uniform(100, 10000),
        ' Fwd Packet Length Max': np_random.uniform(10, 1500),
        ' Fwd Packet Length Min': np_random.uniform(1, 500),
        ' Fwd Packet Length Mean': np_random.uniform(50, 800),
        ' Fwd Packet Length Std': np_random.uniform(1, 300),
        'Bwd Packet Length Max': np_random.uniform(10, 1500),
        ' Bwd Packet Length Min': np_random.uniform(1, 500),
        ' Bwd Packet Length Mean': np_random.uniform(50, 800),
        ' Bwd Packet Length Std': np_random.uniform(1, 300),
        'Flow Bytes/s': np_random.uniform(100, 100000),
        ' Flow Packets/s': np_random.uniform(10, 10000),
        ' Flow IAT Mean': np_random.uniform(1, 1000),
        ' Flow IAT Std': np_random.uniform(1, 500),
        ' Flow IAT Max': np_random.uniform(1, 5000),
        ' Flow IAT Min': np_random.uniform(1, 1000),
        'Fwd IAT Total': np_random.uniform(10, 100000),
        ' Fwd IAT Mean': np_random.uniform(1, 1000),
        ' Fwd IAT Std': np_random.uniform(1, 500),
        ' Fwd IAT Max': np_random.uniform(1, 2000),
        ' Fwd IAT Min': np_random.uniform(1, 500),
        'Bwd IAT Total': np_random.uniform(10, 100000),
        ' Bwd IAT Mean': np_random.uniform(1, 1000),
        ' Bwd IAT Std': np_random.uniform(1, 500),
        ' Bwd IAT Max': np_random.uniform(1, 2000),
        ' Bwd IAT Min': np_random.uniform(1, 500),
        'Fwd PSH Flags': np_random.randint(0, 2),
        ' Bwd PSH Flags': np_random.randint(0, 2),
        ' Fwd URG Flags': np_random.randint(0, 2),
        ' Bwd URG Flags': np_random.randint(0, 2),
        ' Fwd Header Length': np_random.uniform(1, 100),
        ' Bwd Header Length': np_random.uniform(1, 100),
        'Fwd Packets/s': np_random.uniform(10, 10000),
        ' Bwd Packets/s': np_random.uniform(10, 10000),
        ' Min Packet Length': np_random.uniform(10, 1500),
        ' Max Packet Length': np_random.uniform(10, 1500),
        ' Packet Length Mean': np_random.uniform(50, 1000),
        ' Packet Length Std': np_random.uniform(10, 500),
        ' Packet Length Variance': np_random.uniform(100, 10000),
        'FIN Flag Count': np_random.randint(0, 2),
        ' SYN Flag Count': np_random.randint(0, 2),
        ' RST Flag Count': np_random.randint(0, 2),
        ' PSH Flag Count': np_random.randint(0, 2),
        ' ACK Flag Count': np_random.randint(0, 2),
        ' URG Flag Count': np_random.randint(0, 2),
        ' CWE Flag Count': np_random.randint(0, 2),
        ' ECE Flag Count': np_random.randint(0, 2),
        ' Down/Up Ratio': np_random.uniform(0.1, 10),
        ' Average Packet Size': np_random.uniform(100, 2000),
        ' Avg Fwd Segment Size': np_random.uniform(100, 2000),
        ' Avg Bwd Segment Size': np_random.uniform(100, 2000),
        ' Fwd Header Length.1': np_random.uniform(1, 100),
        'Fwd Avg Bytes/Bulk': np_random.uniform(1, 500),
        ' Fwd Avg Packets/Bulk': np_random.uniform(1, 500),
        ' Fwd Avg Bulk Rate': np_random.uniform(1, 500),
        ' Bwd Avg Bytes/Bulk': np_random.uniform(1, 500),
        ' Bwd Avg Packets/Bulk': np_random.uniform(1, 500),
        'Bwd Avg Bulk Rate': np_random.uniform(1, 500),
        'Subflow Fwd Packets': np_random.uniform(1, 10000),
        ' Subflow Fwd Bytes': np_random.uniform(1000, 100000),
        ' Subflow Bwd Packets': np_random.uniform(1, 10000),
        ' Subflow Bwd Bytes': np_random.uniform(1000, 100000),
        'Init_Win_bytes_forward': np_random.uniform(0, 10000),
        ' Init_Win_bytes_backward': np_random.uniform(0, 10000),
        ' act_data_pkt_fwd': np_random.uniform(1, 1000),
        ' min_seg_size_forward': np_random.uniform(1, 100),
        'Active Mean': np_random.uniform(1, 1000),
        ' Active Std': np_random.uniform(1, 500),
        ' Active Max': np_random.uniform(1, 1000),
        ' Active Min': np_random.uniform(1, 500),
        'Idle Mean': np_random.uniform(1, 1000),
        ' Idle Std': np_random.uniform(1, 500),
        ' Idle Max': np_random.uniform(1, 1000),
        ' Idle Min': np_random.uniform(1, 500),
    }
